#!/usr/bin/env bash

# Send an SMS to the Android emulator.
# Copyright (c) 2013, Matthew Caruana Galizia <m@m.cg>
# License: MIT <http://mattcg.mit-license.org/>

DEFAULTNUMBER=5555555555
DEFAULTTEXT="Hi! - aemu"

usage() {
cat << EOF
Send an SMS to the Android emulator.

USAGE:

aemu-sms [options]

OPTIONS:
	-h	Show this message.
	-n	Phone number. Defaults to $DEFAULTNUMBER.
	-m	Message. Will copy from the host clipboard if unspecified.
EOF
}

while getopts "hn:m:" OPTION
do
	case $OPTION in
		h)
			usage
			exit 1
			;;
		n)
			NUMBER=$OPTARG
			;;
		m)
			TEXT=$OPTARG
			;;
	esac
done

if [ -z "$TEXT" ]; then
	# Check that text is coming from a pipe.
	# http://serverfault.com/a/156510/100761
	if [[ $# -lt 1 && -p /dev/stdin ]]; then
		# Read from pipe.
		IFS=$'\n' read -d '' -r -a lines
		for line in "${lines[@]}"; do
			TEXT="$TEXT\n$line"
		done
	fi

	if [ -z "$TEXT" ]; then
		# Read from the clipboard.
		TEXT=`./pbpaste`
		if [ -z "$TEXT" ]; then
			TEXT=$DEFAULTTEXT
		fi
	fi
fi

if [ -z "$NUMBER" ]; then
	NUMBER=$DEFAULTNUMBER
fi

( echo sms send $NUMBER $TEXT; sleep 1; ) | telnet localhost 5554 &> /dev/null
