#!/bin/sh

# Set the prompt for the select command.
PS3="Type a number or 'q' to quit: "

# Check the visual editor.
if [[ -z "$VISUAL" ]]; then
	editor=vi
else
	editor=$VISUAL
fi

# Create a list of files to display.
avdList=$(android list avd -c)
 
# Show a menu and ask for input.
select avdName in $avdList; do
	if [ -n "$avdName" ]; then
		echo "Loading ${avdName} in emulator..."
		emulator -partition-size 512 -avd "${avdName}" &> /dev/null &
		echo "Waiting for remount..."
		sleep 3
		until [[ "${output}" == "remount succeeded" ]]; do
			output=$(adb remount 2> /dev/null)
			sleep 1
		done
		safeFilename=android-hosts.$$.txt
		adb pull /system/etc/hosts /tmp/${safeFilename}
		$editor /tmp/${safeFilename}
		adb push /tmp/${safeFilename} /system/etc/hosts
		rm /tmp/${safeFilename}
	fi
	break
done
