#!/usr/bin/env bash

# Cross-platform pbpaste.
# Copyright (c) 2013, Matthew Caruana Galizia <m@m.cg>
# License: MIT <http://mattcg.mit-license.org/>

if !command -v pbpaste >/dev/null 2>&1; then
	# pbpaste doesn't exist
	# check xsel (http://whereswalden.com/2009/10/23/pbcopy-and-pbpaste-for-linux/)
	if !command -v xsel >/dev/null 2>&1; then
		# check xclip (http://whereswalden.com/2009/10/23/pbcopy-and-pbpaste-for-linux/#comment-137668)
		if !command -v xclip >/dev/null 2>&1; then
			# give up
			TEXT=""
		else
			TEXT=`xclip -selection clipboard -o`
		fi
	else
		TEXT=`xsel --clipboard --output`
	fi
else
	# pbpaste exists
	TEXT=`pbpaste`
fi

echo $TEXT
